services:
  postgres:
    image: postgres:17
    container_name: postrgesql-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - local.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - template-net

volumes:
  postgres_data:

networks:
  template-net:
    driver: bridge