org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.workers.max=3
org.gradle.jvargs=-Xmx4g -Xms1g --XX:MaxMetaspaceSize=1g -XX:+UserParallelGC -Dfile.encoding=UTF-8

org.gradle.configuration-cache=true

projectJavaVersion=25
packageGroup=org.example

# release property
projectVersion = 0.0.1

